name: CI
on:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install dependencies
        run: npm ci
#      - name: Lint affected
#        run: npx nx affected -t lint
#      - name: Test affected
#        run: npx nx affected -t test --configuration=ci
      - name: Build affected
        run: npx nx affected -t build
